import {
  LucideProps,
  Moon,
  SunMedium,
  Twitter,
  type Icon as LucideIcon,
  Menu,
  X,
  Search,
  User,
  LogOut,
  Plus,
  Edit,
  Trash,
  Eye,
  Heart,
  Calendar,
  FileText,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Check,
  Loader2,
  AlertCircle,
  Info,
  Warning,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Link as LinkIcon,
  Mail,
  Lock,
  Github,
  Google,
  Facebook,
  Linkedin,
  Instagram,
  Youtube,
  Globe,
  Settings,
  Bell,
  Bookmark,
  Share,
  MessageSquare,
  ThumbsUp,
  ThumbsDown,
  Star,
  Filter,
  Sort,
  Grid,
  List,
  Clock,
  Tag,
  Hash,
  AtSign,
  Phone,
  MapPin,
  Home,
  Building,
  Briefcase,
  GraduationCap,
  Award,
  Trophy,
  Medal,
  Shield,
  Key,
  Unlock,
  UserPlus,
  Users,
  UserMinus,
  UserX,
  UserCheck,
  UserCog,
  UserEdit,
  UserSearch,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  twitter: Twitter,
  menu: Menu,
  close: X,
  search: Search,
  user: User,
  logout: LogOut,
  plus: Plus,
  edit: Edit,
  trash: Trash,
  eye: Eye,
  heart: Heart,
  calendar: Calendar,
  fileText: FileText,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  check: Check,
  spinner: Loader2,
  alert: AlertCircle,
  info: Info,
  warning: Warning,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  externalLink: ExternalLink,
  link: LinkIcon,
  mail: Mail,
  lock: Lock,
  github: Github,
  google: Google,
  facebook: Facebook,
  linkedin: Linkedin,
  instagram: Instagram,
  youtube: Youtube,
  globe: Globe,
  settings: Settings,
  bell: Bell,
  bookmark: Bookmark,
  share: Share,
  messageSquare: MessageSquare,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  star: Star,
  filter: Filter,
  sort: Sort,
  grid: Grid,
  list: List,
  clock: Clock,
  tag: Tag,
  hash: Hash,
  atSign: AtSign,
  phone: Phone,
  mapPin: MapPin,
  home: Home,
  building: Building,
  briefcase: Briefcase,
  graduationCap: GraduationCap,
  award: Award,
  trophy: Trophy,
  medal: Medal,
  shield: Shield,
  key: Key,
  unlock: Unlock,
  userPlus: UserPlus,
  users: Users,
  userMinus: UserMinus,
  userX: UserX,
  userCheck: UserCheck,
  userCog: UserCog,
  userEdit: UserEdit,
  userSearch: UserSearch,
} 